export const SEARCH_MOVIES = "SEARCH_MOVIES";
export const MOVIES_DATA = "MOVIES_DATA";
export const USUARIOS_REGISTRATION = "USUARIOS_REGISTRATION";
export const USUARIOS_LOGIN = "USUARIOS_LOGIN";
export const USUARIOS_LOGOUT = "USUARIOS_LOGOUT";
export const ADD_FAVORITE = "ADD_FAVORITE";
export const REMOVE_FAVORITE = "REMOVE_FAVORITE";

// export const INPUT_CHANGE = "INPUT_CHANGE";
// export const INPUT_SUBMIT = "INPUT_SUBMIT";
